### ISSUE TITLE
Support dynamically fetched protocol.json for feature detection

### ISSUE THREAD

**Issue by auchenberg** [nojvek/chrome-remote-debug-protocol#3]
Each major runtime are now adding support for the HTTP `json/protocol` endpoint which adds support for dynamically fetched `protocol.json` to allow client feature detection.

This library should probably support this, and not rely on a staticly generated `protocol.json` as the API surface can change from between Chrome versions and when targeting other runtimes.

**Comment by nojvek** [comment]
This library just generates a .d.ts file from protocol.json which is an interface for a proxy-library like `noice-json-rpc`.

What scenario do you have in mind for dynamic protocol.json? Does this mean 'on initialization', the protocol.json is downloaded from client, and typescript attempts to do a type-check on the fly to ensure the client library will work with the endpoint?

**Comment by auchenberg** [comment]
Yes, per client connection, as the `protocol.json` might change depending on what the client connects too. This reality doesn't seem ideal for TypeScript.

**Comment by nojvek** [comment]
I'll add an optional argument to `npm run generate-crdp <url>` If url is present then it will fetch protocol.json from that http url and generate crdp.d.ts. Does that work with you?

**Comment by auchenberg** [comment]
Not really, as the fetching of `protocol.json` would happen on runtime. This library's approach requires a re-generation for each runtime target, and that's potentially one for each Chrome, Edge, Firefox, Webkit, etc version.

**Comment by auchenberg** [comment]
Generating a `crdp.d.ts` makes sense if the client is used towards a stable/fixed set of API's, but the reality even with a standard in place, is that runtime will have runtime specific APIs that will get detected once the client connects.

**Comment by nojvek** [comment]
The churn in chrome's protocol.json happens only in some domains. Most of
the core Api's have been stable.

Let's say you make library X. It calls domain.func(argsobj). The
protocol.json can keep changing but as long as domain.func accepts argsobj,
the library should be fine.

But if the protocol.json ends up changing the name of func or required
params on argsobj, then the library should say protocol incompatible right?

And why not use typescript's typechecker for the compatibility test?

If you look at typescript@next, there are lots of lib.d.ts files for
different es6 and es5 features.

It does make sense to publish version specific .d.ts for each runtime -
major version combination.

Google also hasn't committed to publishing a protocol/json. It might very
well be they'll just point to their git repo source to download the
version.

**Comment by auchenberg** [comment]
I think we are talking past each other. The reality is that the Chrome Debugging Protocol (or whatever the name is in the future) will exist in multiple versions now and in the future. There might be mostly subtle change, but breaking changes will occur. 

The current architecture allows the `protocol.json` to fetched from the given runtime at connection time, which should be used by the client for feature detection to toggle available functionality. This means a given (currently) client can't be generated from a static `protocol.json`, but will have to deal with the uncertainty, as there's already protocol differences between Android device, Chrome desktop instances, and Edge instances, today.

I don't see how generating types for each possible `protocol` variant will solve the problem, as either those types will have to be fetched dynamically or included as a part of the library.

This is much similar to modern web development where feature detection is an integrated part of API. Any future client for Chrome Debugging Protocol should either be able to dynamically adapt it's exposed methods depending on the connect runtime and/or expose logic to perform feature detection. This is probably counter-productive to the nature of TypeScript, but that's the reality.

**Comment by nojvek** [comment]
This issue has been open for a while, @auchenberg , do you have any suggestions on how this project should handle the different versions? The only thing I can think of is having multiple crdp.d.ts files for node/chrome releases.

@roblourens suggestions?

**Comment by roblourens** [comment]
@auchenberg, you're talking about doing stuff at runtime, but the .d.ts is only for building. A library can only be built against one version of the API, and dynamic stuff that happens at runtime has to be handled some other way.

I've been hacking this library to generate a .d.ts from the protocol.json at a given URL, so I can continuously build it against the latest version. I'll send a PR for that soon. And if you had some adapter layer for an older version of the protocol, you can plug in whatever url you want.

**Comment by auchenberg** [comment]
Yes, I'm talking about the usage aspect of this client, and providing a client that's platform agnostic.

Statically generating the client from a fixed version of `protocol.json` might be great for Intelliense, but practically it will allow developers to invoke methods that doesn't exist in a given connected runtime, as the API surface isn't static.

Example: This client is fetching Chrome's `protocol.json` but if used together with WebKit there's will Domains/API's who aren't a part of the client, and calling Chrome-specific API's will fail.

Ideally the client should fetch the `protocol.json` from the runtime on connect, and disable the methods that isn't supported. They could simply throw an exception when invoked. How does that sound?

**Comment by auchenberg** [comment]
@nojvek Chrome has committed to exposing the `protocol.json` over `HTTP /json/protocol`, and the protocol version are exposed via `HTTP /json/version`.

See https://groups.google.com/forum/#!topic/chrome-debugging-protocol/nVGfKGECO-4

**Comment by roblourens** [comment]
Yeah, it is great for intellisense, that's the only point of this repo :)

Handling different versions of the protocol is an open problem but it seems out of scope here.

**Comment by nojvek** [comment]
Closing this as the ask is out of scope for the repo.
